Repository SU-ZIP/SUZIP-Backend, pull requests merged in 2024-05, with the labels that each got.

#54 [Feat] 프론트 연동 관련 수정
  src/main/java/Fo/Suzip/config/CorsMvcConfig.java
  src/main/java/Fo/Suzip/web/controller/AuthController.java
  src/main/java/Fo/Suzip/web/controller/ContentController.java
  src/main/java/Fo/Suzip/web/controller/EmotionController.java
  src/main/java/Fo/Suzip/web/controller/MemberController.java
  src/main/java/Fo/Suzip/web/controller/ScrapController.java
  src/main/resources/templates/login.html
Labels: :sparkles: feature

#56 [Feat] access 토큰 재발급및 cors 수정
  src/main/java/Fo/Suzip/apiPayload/exception/handler/MyAuthenticationSuccessHandler.java
  src/main/java/Fo/Suzip/apiPayload/exception/handler/TokenHandler.java
  src/main/java/Fo/Suzip/config/SecurityConfig.java
  src/main/java/Fo/Suzip/converter/JwtConverter.java
  src/main/java/Fo/Suzip/converter/MemberConverter.java
  src/main/java/Fo/Suzip/domain/RefreshToken.java
  src/main/java/Fo/Suzip/jwt/JwtAuthFilter.java
  src/main/java/Fo/Suzip/jwt/JwtUtil.java
  src/main/java/Fo/Suzip/repository/RefreshTokenRepository.java
  src/main/java/Fo/Suzip/service/MemberService.java
  src/main/java/Fo/Suzip/service/RefreshTokenService.java
  src/main/java/Fo/Suzip/web/controller/AuthController.java
  src/main/java/Fo/Suzip/web/controller/OAuth2RedirectController.java
  src/main/java/Fo/Suzip/web/dto/authDTO/GeneratedToken.java
  src/main/java/Fo/Suzip/web/dto/memberDTO/MemberResponseDTO.java
  src/main/resources/application-local.yml
  src/main/resources/static/css/styles.css
  src/main/resources/templates/login.html
Labels: :sparkles: feature, fix

#57 [Fix] 로그아웃API 오류 수정
  src/main/java/Fo/Suzip/apiPayload/exception/handler/MyAuthenticationSuccessHandler.java
  src/main/java/Fo/Suzip/jwt/JwtAuthFilter.java
  src/main/java/Fo/Suzip/jwt/JwtUtil.java
  src/main/java/Fo/Suzip/service/RefreshTokenService.java
  src/main/java/Fo/Suzip/web/controller/AuthController.java
Labels: fix

#58 [Fix] 토큰 길이 연장
  src/main/java/Fo/Suzip/domain/RefreshToken.java
  src/main/java/Fo/Suzip/web/controller/AuthController.java
Labels: fix

#59 [Fix] 일기 저장 프론트 연동
  src/main/java/Fo/Suzip/apiPayload/code/status/ErrorStatus.java
  src/main/java/Fo/Suzip/jwt/JwtAuthFilter.java
  src/main/java/Fo/Suzip/web/controller/AuthController.java
  src/main/java/Fo/Suzip/web/controller/DiaryController.java
  src/main/resources/application-local.yml
Labels: fix

#60 [Fix] 일기 조회 리스트 갯수 5개로 수정
  src/main/java/Fo/Suzip/service/DiaryService/DiaryServiceImpl.java
Labels: fix

#61 [Fix] 일기 전체 조회 작성 날짜 추가
  src/main/java/Fo/Suzip/converter/DiaryConverter.java
  src/main/java/Fo/Suzip/web/dto/diaryDTO/DiaryResponseDTO.java
Labels: fix

#62 [Fix] 일기조회 아이디 리턴 추가
  src/main/java/Fo/Suzip/converter/DiaryConverter.java
  src/main/java/Fo/Suzip/web/dto/diaryDTO/DiaryResponseDTO.java
Labels: fix

#63 [Fix] 일기수정 Api 이미지 수정 추가
  src/main/java/Fo/Suzip/domain/Diary.java
  src/main/java/Fo/Suzip/service/DiaryService/DiaryService.java
  src/main/java/Fo/Suzip/service/DiaryService/DiaryServiceImpl.java
  src/main/java/Fo/Suzip/web/controller/DiaryController.java
  src/main/java/Fo/Suzip/web/dto/diaryDTO/DiaryRequestDTO.java
  src/main/java/Fo/Suzip/web/dto/diaryDTO/DiaryResponseDTO.java
Labels: :sparkles: feature, fix

#64 [Fix] 일기수정 Api 컨버터 이미지 url 추가
  src/main/java/Fo/Suzip/converter/DiaryConverter.java
Labels: fix

#65 [Fix] 일기등록시 이미 등록된 감정이면 작성 안되는 문제 해결
  src/main/java/Fo/Suzip/converter/DiaryConverter.java
  src/main/java/Fo/Suzip/domain/Diary.java
  src/main/java/Fo/Suzip/domain/DiaryEmotion.java
  src/main/java/Fo/Suzip/repository/EmotionRepository.java
  src/main/java/Fo/Suzip/service/DiaryService/DiaryServiceImpl.java
  src/main/java/Fo/Suzip/service/emotionService/EmotionQueryServiceImpl.java
  src/main/java/Fo/Suzip/web/controller/DiaryController.java
  src/main/java/Fo/Suzip/web/dto/diaryDTO/DiaryResponseDTO.java
  src/main/resources/application-local.yml
Labels: fix

#66 [Feat] 작성한 일기 날짜 필드 추가
  src/main/java/Fo/Suzip/converter/DiaryConverter.java
  src/main/java/Fo/Suzip/domain/Diary.java
  src/main/java/Fo/Suzip/web/dto/diaryDTO/DiaryRequestDTO.java
  src/main/java/Fo/Suzip/web/dto/diaryDTO/DiaryResponseDTO.java
  src/main/resources/application-local.yml
Labels: :sparkles: feature

#68 [Feat] 일기 수정하기 이미지 오류 해결
  src/main/java/Fo/Suzip/domain/Diary.java
  src/main/java/Fo/Suzip/service/DiaryService/DiaryServiceImpl.java
  src/main/java/Fo/Suzip/web/dto/diaryDTO/DiaryRequestDTO.java
Labels: :sparkles: feature

#69 [Fix] 사용자 정보 수정 관련 필드 추가 및 이름 변경
  src/main/java/Fo/Suzip/service/MemberService.java
  src/main/java/Fo/Suzip/web/dto/memberDTO/MemberResponseDTO.java
Labels: fix

#70 [Fix] 사용자 정보 수정 관련 컨버터 수정
  src/main/java/Fo/Suzip/converter/MemberConverter.java
  src/main/java/Fo/Suzip/web/dto/memberDTO/MemberResponseDTO.java
Labels: fix

#71 [Fix] 사용자 프로필 이미지 s3 저장되게 수정
  src/main/java/Fo/Suzip/service/MemberService.java
  src/main/java/Fo/Suzip/web/controller/MemberController.java
  src/main/java/Fo/Suzip/web/dto/memberDTO/MemberRequestDTO.java
Labels: fix

#72 [Fix] 유저 정보 변경 API 미디어 타입 수정
  src/main/java/Fo/Suzip/web/controller/MemberController.java
Labels: fix

#74 [Fix] 회원 탈퇴 기능 수정
  .DS_Store
  src/.DS_Store
  src/main/java/Fo/Suzip/repository/DiaryRepository.java
  src/main/java/Fo/Suzip/service/MemberService.java
  src/main/java/Fo/Suzip/web/controller/AuthController.java
  src/main/java/Fo/Suzip/web/controller/MemberController.java
Labels: fix

#75 [Feat] 일기 정렬기능 오름차순, 내림차순 구현
  src/main/java/Fo/Suzip/repository/DiaryRepository.java
  src/main/java/Fo/Suzip/service/DiaryService/DiaryService.java
  src/main/java/Fo/Suzip/service/DiaryService/DiaryServiceImpl.java
  src/main/java/Fo/Suzip/web/controller/DiaryController.java
Labels: :sparkles: feature

#76 [Fix] 액세스토큰 재발급 오류 임시 수정
  src/main/java/Fo/Suzip/config/SecurityConfig.java
  src/main/java/Fo/Suzip/domain/Diary.java
  src/main/java/Fo/Suzip/domain/RefreshToken.java
  src/main/java/Fo/Suzip/jwt/JwtAuthFilter.java
  src/main/java/Fo/Suzip/jwt/JwtUtil.java
  src/main/java/Fo/Suzip/service/RefreshTokenService.java
Labels: fix

#77 [Fix] 리프레시 토큰 재발급 오류 수정
  src/main/java/Fo/Suzip/domain/RefreshToken.java
  src/main/java/Fo/Suzip/jwt/JwtAuthFilter.java
  src/main/java/Fo/Suzip/jwt/JwtUtil.java
  src/main/java/Fo/Suzip/service/DiaryService/DiaryServiceImpl.java
  src/main/java/Fo/Suzip/service/RefreshTokenService.java
  src/main/resources/application-local.yml
Labels: fix

#78 [Fix] 리프레시 토큰 레포지터리 PK 타입 오타 수정
  src/main/java/Fo/Suzip/jwt/JwtAuthFilter.java
  src/main/java/Fo/Suzip/repository/RefreshTokenRepository.java
  src/main/resources/application-local.yml
Labels: fix

#79 [Fix] 배포 오류 수정
  src/main/java/Fo/Suzip/apiPayload/exception/handler/MyAuthenticationFailureHandler.java
  src/main/java/Fo/Suzip/jwt/JwtAuthFilter.java
  src/main/java/Fo/Suzip/web/controller/DiaryController.java
  src/main/resources/templates/login.html
Labels: fix

#82 [Fix] url 환경변수 수정
  src/main/java/Fo/Suzip/config/SecurityConfig.java
  src/main/java/Fo/Suzip/config/WebConfig.java
Labels: fix

#83 [Feat] Fastapi Spring 연동
  build.gradle
  src/main/java/Fo/Suzip/web/controller/DiaryController.java
Labels: :sparkles: feature

#84 AnalyzeService 클래스 생성
  src/main/java/Fo/Suzip/service/analyzeService/AnalyzeService.java
  src/main/java/Fo/Suzip/service/analyzeService/AnalyzeServiceImpl.java
  src/main/java/Fo/Suzip/web/controller/DiaryController.java
  src/main/java/Fo/Suzip/web/dto/diaryDTO/DiaryResponseDTO.java
Labels: :sparkles: feature

#85 [Feat] AI 연동 및 컨텐츠 저장 구현
  src/main/java/Fo/Suzip/converter/ContentConverter.java
  src/main/java/Fo/Suzip/converter/DiaryConverter.java
  src/main/java/Fo/Suzip/domain/BaseEntity.java
  src/main/java/Fo/Suzip/domain/Member.java
  src/main/java/Fo/Suzip/domain/MemberRecommendedItem.java
  src/main/java/Fo/Suzip/domain/contentItem/Book.java
  src/main/java/Fo/Suzip/domain/contentItem/ContentItem.java
  src/main/java/Fo/Suzip/domain/contentItem/Movie.java
  src/main/java/Fo/Suzip/domain/contentItem/Music.java
  src/main/java/Fo/Suzip/repository/ContentRepository.java
  src/main/java/Fo/Suzip/repository/MemberRecommendedItemRepository.java
  src/main/java/Fo/Suzip/service/DiaryService/DiaryService.java
  src/main/java/Fo/Suzip/service/DiaryService/DiaryServiceImpl.java
  src/main/java/Fo/Suzip/service/analyzeService/AnalyzeService.java
  src/main/java/Fo/Suzip/service/analyzeService/AnalyzeServiceImpl.java
  src/main/java/Fo/Suzip/service/contentService/ContentCommandService.java
  src/main/java/Fo/Suzip/service/contentService/ContentCommandServiceImpl.java
  src/main/java/Fo/Suzip/web/controller/DiaryController.java
  src/main/java/Fo/Suzip/web/dto/diaryDTO/DiaryResponseDTO.java
Labels: :sparkles: feature

#86 [Fix] 컬럼길이 500자이상 안 넘게 수정
  src/main/java/Fo/Suzip/converter/ContentConverter.java
  src/main/java/Fo/Suzip/domain/contentItem/ContentItem.java
  src/main/java/Fo/Suzip/web/dto/diaryDTO/DiaryResponseDTO.java
  src/main/resources/application-local.yml
Labels: fix

#87 [Feat/Fix] 일기 페이지 검색 및 정렬 수정
  src/main/java/Fo/Suzip/converter/DiaryConverter.java
  src/main/java/Fo/Suzip/domain/contentItem/ContentItem.java
  src/main/java/Fo/Suzip/repository/DiaryRepository.java
  src/main/java/Fo/Suzip/service/DiaryService/DiaryService.java
  src/main/java/Fo/Suzip/service/DiaryService/DiaryServiceImpl.java
  src/main/java/Fo/Suzip/web/controller/DiaryController.java
  src/main/java/Fo/Suzip/web/dto/diaryDTO/DiaryResponseDTO.java
  src/main/resources/application-local.yml
Labels: :sparkles: feature, fix

#88 [Feat]분석페이지 조회 기능 구현
  src/main/java/Fo/Suzip/converter/ContentConverter.java
  src/main/java/Fo/Suzip/converter/DiaryConverter.java
  src/main/java/Fo/Suzip/domain/Diary.java
  src/main/java/Fo/Suzip/repository/ContentRepository.java
  src/main/java/Fo/Suzip/service/DiaryService/DiaryService.java
  src/main/java/Fo/Suzip/service/DiaryService/DiaryServiceImpl.java
  src/main/java/Fo/Suzip/service/contentService/ContentCommandServiceImpl.java
  src/main/java/Fo/Suzip/web/controller/DiaryController.java
  src/main/java/Fo/Suzip/web/dto/diaryDTO/DiaryResponseDTO.java
Labels: :sparkles: feature

#90 [Fix] 일기 작성시 컨텐츠 아이디 안나오는 오류 해결
  src/main/java/Fo/Suzip/web/controller/DiaryController.java
Labels: fix

#91 [Fix] 감정 매핑 오류 수정
  src/main/java/Fo/Suzip/service/DiaryService/DiaryService.java
  src/main/java/Fo/Suzip/service/DiaryService/DiaryServiceImpl.java
  src/main/java/Fo/Suzip/web/controller/DiaryController.java
Labels: fix

#92 [Fix] 컨텐츠 스크랩 요청 dto 수정
  src/main/java/Fo/Suzip/web/dto/scrapDTO/ScrapRequestDTO.java
Labels: fix

#94 [Fix] 분석페이지 색 안나오는 오류 수정
  src/main/java/Fo/Suzip/converter/DiaryConverter.java
Labels: fix

#95 [Fix] switch 오류 해결
  src/main/java/Fo/Suzip/converter/DiaryConverter.java
Labels: fix

#96 [Feat] 한달 간의 감정 조회 api
  src/main/java/Fo/Suzip/repository/DiaryRepository.java
  src/main/java/Fo/Suzip/repository/EmotionRepository.java
  src/main/java/Fo/Suzip/repository/MemberItemRepository.java
  src/main/java/Fo/Suzip/service/contentService/ContentQueryService.java
  src/main/java/Fo/Suzip/service/contentService/ContentQueryServiceImpl.java
  src/main/java/Fo/Suzip/service/emotionService/EmotionQueryService.java
  src/main/java/Fo/Suzip/service/emotionService/EmotionQueryServiceImpl.java
  src/main/java/Fo/Suzip/web/controller/EmotionController.java
  src/main/java/Fo/Suzip/web/controller/ScrapController.java
  src/main/java/Fo/Suzip/web/dto/contentDTO/ContentResponseDTO.java
  src/main/java/Fo/Suzip/web/dto/emotionDTO/EmotionResponseDto.java
Labels: :sparkles: feature

#97 [Fix] 한달 감정 조회 일기 아이디 필드 추가
  src/main/java/Fo/Suzip/service/emotionService/EmotionQueryServiceImpl.java
  src/main/java/Fo/Suzip/web/dto/emotionDTO/EmotionResponseDto.java
Labels: fix

#98 [Fix] 일기 삭제 문제 해결
  src/main/java/Fo/Suzip/repository/MemberRecommendedItemRepository.java
  src/main/java/Fo/Suzip/service/DiaryService/DiaryServiceImpl.java
Labels: fix

#101 [Fix] 로그인 화면 수정
  src/main/java/Fo/Suzip/config/WebConfig.java
  src/main/java/Fo/Suzip/converter/ContentConverter.java
  src/main/java/Fo/Suzip/web/dto/contentDTO/ContentResponseDTO.java
  src/main/resources/static/css/styles.css
  src/main/resources/static/fonts/Font.css
  src/main/resources/static/fonts/MonumentExtended-Ultrabold.otf
  src/main/resources/static/fonts/Pretendard-Black.otf
  src/main/resources/static/fonts/Pretendard-Bold.otf
  src/main/resources/static/fonts/Pretendard-ExtraBold.otf
  src/main/resources/static/fonts/Pretendard-ExtraLight.otf
  src/main/resources/static/fonts/Pretendard-Light.otf
  src/main/resources/static/fonts/Pretendard-Medium.otf
  src/main/resources/static/fonts/Pretendard-Regular.otf
  src/main/resources/static/fonts/Pretendard-SemiBold.otf
  src/main/resources/static/fonts/Pretendard-Thin.otf
  src/main/resources/templates/login.html
Labels: fix

#110 Commits on May 24, 2024 [Fix] 로그인 수정
  src/main/resources/templates/login.html
Labels: fix

#111 [Fix] 회원가입 페이지 헤더 수정
  src/main/resources/templates/signup.html
Labels: fix
